name: RailsTest

on:
  push:
    branches:
      - master
      - develop
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      image: mysql:5.7

    container:
      image: ruby:2.6.3
      env:
        RAILD_ENV: test
        MYSQL_ALLOW_EMPTY_PASSWORD: 1

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Prepare bundler
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3

    - name: Run tests with ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Prepare yarn
      run: yarn install

    - name: Prepare database
      run: |
        bin/rails db:create
        bin/raild db:migrate

    - name: Run rubocop
      run: |
        rubocop

    - name: Run rspec
      run: |
        rspec
