name: RailsTest

on:
  push:
    branches:
      - master
      - develop
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      image: mysql:5.7

    container:
      image: ruby:2.6.3
      env:
        RAILD_ENV: test
        MYSQL_ALLOW_EMPTY_PASSWORD: 1

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Cache bundle directory
      uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gem-

    - name: Prepare bundler
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Prepare yarn
      run: |
        npm install -g yarn
        yarn install

    - name: Verify MySQL connection from host
      run: |
        sudo apt-get install -y mysql-client
        mysql --host 127.0.0.1 --port ${{ job.services.mysql.ports['3306'] }} -uroot -ppassword -e "SHOW DATABASES"

    - name: Prepare database
      run: |
        bin/rails db:create
        bin/raild db:migrate

    - name: Run rubocop
      run: |
        rubocop

    - name: Run rspec
      run: |
        rspec
