name: RailsTest

on:
  push:
    branches:
      - master
      - develop
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password

    container:
      image: ruby:2.6.3
      env:
        RAILS_ENV: test
        MYSQL_ALLOW_EMPTY_PASSWORD: 1

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Cache bundle directory
      uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: bundle-${{ hashFiles('**/Gemfile.lock') }}

    - name: Prepare bundler
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3

    - name: Cache node_modules
      uses: actions/cache@v1
      with:
        path: node_modules
        key: yarn-${{ hashFiles('**/yarn.lock') }}

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Prepare yarn
      run: |
        npm install -g yarn
        yarn install

    - name: set database.yml
      run: cp -v config/database.ci.yml config/database.yml

    - name: Prepare database
      run: |
        bundle exec rails db:create db:schema:load --trace

    - name: Run rubocop
      run: bundle exec rubocop

    - name: Run rspec
      run: bundle exec rspec
